name: Build wheels (cibuildwheel)
description: Build and test wheels for a single OS/arch combination using cibuildwheel.

inputs:
  platform:
    description: "linux|macos|windows"
    required: true
  arch:
    description: "x86_64|aarch64|arm64|AMD64"
    required: true
  build:
    description: "cibuildwheel build selector (e.g. cp314-* cp314t-*)"
    required: false
    default: "cp310-* cp311-* cp312-* cp313-* cp314-* cp314t-*"
  artifact_name:
    description: "Artifact name to upload wheels under"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - uses: dtolnay/rust-toolchain@stable

    - uses: astral-sh/setup-uv@v7

    - name: Install Rust target (macos x86_64)
      if: ${{ inputs.platform == 'macos' && inputs.arch == 'x86_64' }}
      shell: bash
      run: rustup target add x86_64-apple-darwin

    - name: Install Rust target (macos arm64)
      if: ${{ inputs.platform == 'macos' && inputs.arch == 'arm64' }}
      shell: bash
      run: rustup target add aarch64-apple-darwin

    - name: Set up QEMU (linux aarch64)
      if: ${{ inputs.platform == 'linux' && inputs.arch == 'aarch64' }}
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx (linux)
      if: ${{ inputs.platform == 'linux' }}
      uses: docker/setup-buildx-action@v3

    - name: Build manylinux image (linux x86_64)
      if: ${{ inputs.platform == 'linux' && inputs.arch == 'x86_64' }}
      shell: bash
      run: |
        set -euo pipefail
        docker build -t jsrun-manylinux-x86_64 -f .github/docker/Dockerfile.x86_64 .
        docker image ls jsrun-manylinux-x86_64

    - name: Build manylinux image (linux aarch64)
      if: ${{ inputs.platform == 'linux' && inputs.arch == 'aarch64' }}
      shell: bash
      run: |
        set -euo pipefail
        docker buildx build --load --platform linux/arm64 -t jsrun-manylinux-aarch64 -f .github/docker/Dockerfile.aarch64 .
        docker image ls jsrun-manylinux-aarch64

    - name: Build wheels (linux x86_64)
      if: ${{ inputs.platform == 'linux' && inputs.arch == 'x86_64' }}
      uses: pypa/cibuildwheel@v3.3.1
      env:
        CIBW_BUILD: ${{ inputs.build }}
        CIBW_BUILD_VERBOSITY: "1"
        CIBW_MANYLINUX_X86_64_IMAGE: "jsrun-manylinux-x86_64"
        CIBW_OUTPUT_DIR: "wheelhouse"
        CIBW_ARCHS_LINUX: "x86_64"

    - name: Build wheels (linux aarch64)
      if: ${{ inputs.platform == 'linux' && inputs.arch == 'aarch64' }}
      uses: pypa/cibuildwheel@v3.3.1
      env:
        CIBW_BUILD: ${{ inputs.build }}
        CIBW_BUILD_VERBOSITY: "1"
        CIBW_MANYLINUX_AARCH64_IMAGE: "jsrun-manylinux-aarch64"
        CIBW_OUTPUT_DIR: "wheelhouse"
        CIBW_ARCHS_LINUX: "aarch64"

    - name: Build wheels
      if: ${{ inputs.platform == 'macos' }}
      uses: pypa/cibuildwheel@v3.3.1
      env:
        CIBW_BUILD: ${{ inputs.build }}
        CIBW_BUILD_VERBOSITY: "1"
        CIBW_OUTPUT_DIR: "wheelhouse"
        CIBW_ARCHS_MACOS: ${{ inputs.arch }}

    - name: Build wheels
      if: ${{ inputs.platform == 'windows' }}
      uses: pypa/cibuildwheel@v3.3.1
      env:
        CIBW_BUILD: ${{ inputs.build }}
        CIBW_BUILD_VERBOSITY: "1"
        CIBW_OUTPUT_DIR: "wheelhouse"
        CIBW_ARCHS_WINDOWS: ${{ inputs.arch }}

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: wheelhouse/*
